### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by zmr** [tesserae/tesserae#15]
Is there any documentation on how to get this up and running? How does it work with non-English texts (or rather texts with radically different tokenization requirements than English?)?

**Comment by cwf2** [comment]
I'm afraid the short answer is no, there isn't any good documentation right now. There's a [vagrant-based](https://github.com/cwf2/tess_vagrant) implementation in the works, which we expect to be ready around July. We will report back on progress in the next months. At the same time, the whole project is ultimately slated to be replaced by [this](https://github.com/eberle1080/tesserae-ng).

**Comment by jamesgawley** [comment]
I'm not sure about non-english texts, though theoretically it should work for anything Unicode.
